aws_region = "us-east-1"
project_name = "droneedge-dev"
domain_name = "thedroneedge.com"
api_subdomain = "api"
frontend_subdomain = "app"
stripe_publishable_key = "pk_test_51T1cg92Rw6cpyMyJI6BOeozOuntx5b1qpgz6yyKfiJZpJMQCclii0IRATMtCQhRknFkJ52JnG2dRSX7CKsYDet8S00WqOUxzWc"
email_enabled = true
email_host = "smtp-relay.gmail.com"
email_port = 587
email_from = "DroneEdge <donotreply@thedroneedge.com>"
admin_email = "james@thedroneedge.com"
