version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
      - /Users/jamesspaniak/certs:/ssl/
  api_server:
    container_name: api_server
    image: node:16
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=blog
    depends_on:
      - postgres
      - nginx
  drone:
    build: ./drone
    image: node:18
    ports:
      - "8080:8080"
    volumes:
      - ./drone:/app
    environment:
      - NODE_ENV=dev
networks:
  default: