version: "3.9" # TODO When deploying, set to only one file: docker-compose -f docker-compose.yml up --build -d
services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
      - /Users/jamesspaniak/certs:/ssl/
  api_server:
    container_name: api_server
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=blog
    depends_on:
      - postgres
      - nginx
  drone:
    container_name: drone
    build:
      context: .
      dockerfile: drone/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
networks:
  default: