/**
 * Canonical static asset paths for metadata, JSON-LD, and UI.
 * Default social preview image is generated by `app/opengraph-image.tsx` (not `public/og-default.png`).
 */
export const SITE_ASSETS = {
  /** SVG favicon (`app/icon.svg`); browsers that prefer raster can use `iconPng`. */
  favicon: '/icon.svg',
  /** Raster mark for Apple touch / contexts that reject or mishandle SVG (place at `public/icon.png`). */
  iconPng: '/icon.png',
  brandMark: '/brand-mark.svg',
  wordmark: '/logo.svg',
} as const;

/** Theme colors aligned with `globals.css` (SSR / browser chrome; in-app theme still uses `data-theme`). */
export const THEME_COLOR = {
  dark: '#0d0d0d',
  light: '#fafafa',
} as const;
