export enum AuditAction {
    LOGIN = 'LOGIN',
    REGISTER = 'REGISTER',
    VERIFY_EMAIL = 'VERIFY_EMAIL',
    COURSE_STARTED = 'COURSE_STARTED',
    UNIT_COMPLETED = 'UNIT_COMPLETED',
    EXAM_SUBMITTED = 'EXAM_SUBMITTED',
    COURSE_COMPLETED = 'COURSE_COMPLETED',
    PROGRESS_RESET = 'PROGRESS_RESET',
    COURSE_PURCHASED = 'COURSE_PURCHASED',
    PRO_UPGRADE = 'PRO_UPGRADE',
}
